/*
 * Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com).
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.is.migration.service.v600.dao;

import org.wso2.carbon.identity.core.migrate.MigrationClientException;
import org.wso2.carbon.identity.core.util.IdentityDatabaseUtil;
import org.wso2.carbon.is.migration.service.v530.SQLConstants;
import org.wso2.carbon.is.migration.service.v530.util.JDBCPersistenceUtil;
import org.wso2.carbon.utils.DBUtils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ApplicationDAO {

    private static final String ADD_ACCESS_URL = "UPDATE SP_APP " +
            "SET ACCESS_URL = ? " +
            "WHERE APP_NAME= ? AND TENANT_ID= ? ";


    public void updateAccessURL(Connection connection, String application, String accessURL, int
            tenantID)
            throws MigrationClientException {

        PreparedStatement prepStmt = null;
        try {
            boolean autoCommitStatus = connection.getAutoCommit();
            connection.setAutoCommit(false);
            String dbProductName = connection.getMetaData().getDatabaseProductName();
            prepStmt = connection.prepareStatement(ADD_ACCESS_URL,
                    new String[]{DBUtils.getConvertedAutoGeneratedColumnName
                            (dbProductName, SQLConstants.ID_COLUMN)});
            prepStmt.setString(1, accessURL);
            prepStmt.setString(2, application);
            prepStmt.setInt(3, tenantID);
            prepStmt.executeUpdate();
            JDBCPersistenceUtil.commitTransaction(connection);
            connection.setAutoCommit(autoCommitStatus);
        } catch (SQLException e) {
            JDBCPersistenceUtil.rollbackTransaction(connection);
            throw new MigrationClientException("Error while inserting AccessURL value.", e);
        } finally {
            IdentityDatabaseUtil.closeStatement(prepStmt);
        }
    }
}
