package org.wso2.carbon.is.migration.service.v5120.dao;

import org.wso2.carbon.identity.core.migrate.MigrationClientException;
import org.wso2.carbon.identity.core.util.IdentityDatabaseUtil;
import org.wso2.carbon.is.migration.service.v530.SQLConstants;
import org.wso2.carbon.is.migration.service.v530.util.JDBCPersistenceUtil;
import org.wso2.carbon.utils.DBUtils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ApplicationDAO {

    private static final String ADD_ACCESS_URL = "UPDATE SP_APP " +
            "SET ACCESS_URL = ? " +
            "WHERE APP_NAME= ? AND TENANT_ID= ? ";


    public void updateAccessURL(Connection connection, String application, String accessURL, int
            tenantID)
            throws MigrationClientException {

        PreparedStatement prepStmt = null;
        try {
            boolean autoCommitStatus = connection.getAutoCommit();
            connection.setAutoCommit(false);
            String dbProductName = connection.getMetaData().getDatabaseProductName();
            prepStmt = connection.prepareStatement(ADD_ACCESS_URL,
                    new String[]{DBUtils.getConvertedAutoGeneratedColumnName
                            (dbProductName, SQLConstants.ID_COLUMN)});
            prepStmt.setString(1, accessURL);
            prepStmt.setString(2, application);
            prepStmt.setInt(3, tenantID);
            prepStmt.executeUpdate();
            JDBCPersistenceUtil.commitTransaction(connection);
            connection.setAutoCommit(autoCommitStatus);
        } catch (SQLException e) {
            JDBCPersistenceUtil.rollbackTransaction(connection);
            throw new MigrationClientException("Error while inserting AccessURL value.", e);
        } finally {
            IdentityDatabaseUtil.closeStatement(prepStmt);
        }
    }
}
