DROP SEQUENCE IF EXISTS CM_SP_PURPOSE_PURPOSE_CAT_ASSC_PK_SEQ;
CREATE SEQUENCE CM_SP_PURPOSE_PURPOSE_CAT_ASSC_PK_SEQ;
ALTER TABLE CM_SP_PURPOSE_PURPOSE_CAT_ASSC ADD ID INTEGER DEFAULT NEXTVAL('CM_SP_PURPOSE_PURPOSE_CAT_ASSC_PK_SEQ') PRIMARY KEY;

DROP SEQUENCE IF EXISTS CM_PURPOSE_PII_CAT_ASSOC_PK_SEQ;
CREATE SEQUENCE CM_PURPOSE_PII_CAT_ASSOC_PK_SEQ;
ALTER TABLE CM_PURPOSE_PII_CAT_ASSOC ADD ID INTEGER DEFAULT NEXTVAL('CM_PURPOSE_PII_CAT_ASSOC_PK_SEQ') PRIMARY KEY;

DROP SEQUENCE IF EXISTS CM_SP_PURPOSE_PII_CAT_ASSOC_PK_SEQ;
CREATE SEQUENCE CM_SP_PURPOSE_PII_CAT_ASSOC_PK_SEQ;
ALTER TABLE CM_SP_PURPOSE_PII_CAT_ASSOC ADD ID INTEGER DEFAULT NEXTVAL('CM_SP_PURPOSE_PII_CAT_ASSOC_PK_SEQ') PRIMARY KEY;

DROP SEQUENCE IF EXISTS CM_CONSENT_RECEIPT_PROPERTY_PK_SEQ;
CREATE SEQUENCE CM_CONSENT_RECEIPT_PROPERTY_PK_SEQ;
ALTER TABLE CM_CONSENT_RECEIPT_PROPERTY ADD ID INTEGER DEFAULT NEXTVAL('CM_CONSENT_RECEIPT_PROPERTY_PK_SEQ') PRIMARY KEY;
