DROP SEQUENCE IF EXISTS REG_RESOURCE_COMMENT_PK_SEQ;
CREATE SEQUENCE REG_RESOURCE_COMMENT_PK_SEQ;
ALTER TABLE REG_RESOURCE_COMMENT ADD ID INTEGER DEFAULT NEXTVAL('REG_RESOURCE_COMMENT_PK_SEQ') PRIMARY KEY;

DROP SEQUENCE IF EXISTS REG_RESOURCE_RATING_PK_SEQ;
CREATE SEQUENCE REG_RESOURCE_RATING_PK_SEQ;
ALTER TABLE REG_RESOURCE_RATING ADD ID INTEGER DEFAULT NEXTVAL('REG_RESOURCE_RATING_PK_SEQ') PRIMARY KEY;

DROP SEQUENCE IF EXISTS REG_RESOURCE_TAG_PK_SEQ;
CREATE SEQUENCE REG_RESOURCE_TAG_PK_SEQ;
ALTER TABLE REG_RESOURCE_TAG ADD ID INTEGER DEFAULT NEXTVAL('REG_RESOURCE_TAG_PK_SEQ') PRIMARY KEY;

DROP SEQUENCE IF EXISTS REG_RESOURCE_PROPERTY_PK_SEQ;
CREATE SEQUENCE REG_RESOURCE_PROPERTY_PK_SEQ;
ALTER TABLE REG_RESOURCE_PROPERTY ADD ID INTEGER DEFAULT NEXTVAL('REG_RESOURCE_PROPERTY_PK_SEQ') PRIMARY KEY;

DROP SEQUENCE IF EXISTS UM_SHARED_USER_ROLE_PK_SEQ;
CREATE SEQUENCE UM_SHARED_USER_ROLE_PK_SEQ;
ALTER TABLE UM_SHARED_USER_ROLE ADD ID INTEGER DEFAULT NEXTVAL('UM_SHARED_USER_ROLE_PK_SEQ') PRIMARY KEY;
