CREATE TABLE IF NOT EXISTS IDN_USER_FUNCTIONALITY_MAPPING (
    ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    FUNCTIONALITY_ID VARCHAR(255) NOT NULL,
    IS_FUNCTIONALITY_LOCKED BOOLEAN(1) NOT NULL,
    FUNCTIONALITY_UNLOCK_TIME BIGINT NOT NULL,
    FUNCTIONALITY_LOCK_REASON VARCHAR(1023),
    FUNCTIONALITY_LOCK_REASON_CODE VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT IDN_USER_FUNCTIONALITY_MAPPING_CONSTRAINT UNIQUE (USER_ID, TENANT_ID, FUNCTIONALITY_ID)
);

CREATE TABLE IF NOT EXISTS IDN_USER_FUNCTIONALITY_PROPERTY (
    ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    FUNCTIONALITY_ID VARCHAR(255) NOT NULL,
    PROPERTY_NAME VARCHAR(255),
    PROPERTY_VALUE VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT IDN_USER_FUNCTIONALITY_PROPERTY_CONSTRAINT UNIQUE (USER_ID, TENANT_ID, FUNCTIONALITY_ID, PROPERTY_NAME)
);
