CREATE OR REPLACE PROCEDURE ALTER_IDN_OAUTH2_DEVICE_FLOW
BEGIN ATOMIC
    IF EXISTS(SELECT * FROM SYSCAT.TABLES WHERE TABNAME='IDN_OAUTH2_DEVICE_FLOW')
    THEN
        IF NOT EXISTS(SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME='IDN_OAUTH2_DEVICE_FLOW' AND COLNAME='QUANTIFIER')
        THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_DEVICE_FLOW ADD COLUMN QUANTIFIER INTEGER DEFAULT 0';
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_DEVICE_FLOW DROP CONSTRAINT USER_CODE';
            EXECUTE IMMEDIATE 'ALTER TABLE IDN_OAUTH2_DEVICE_FLOW ADD CONSTRAINT USRCDE_QNTFR_CONSTRAINT UNIQUE (USER_CODE, QUANTIFIER)';
        END IF;
    END IF;
END
/

CALL ALTER_IDN_OAUTH2_DEVICE_FLOW
/

DROP PROCEDURE ALTER_IDN_OAUTH2_DEVICE_FLOW
/
