IF NOT EXISTS (SELECT * FROM SYS.indexes WHERE name = 'IDX_TK_VALUE_TYPE' and object_id = OBJECT_ID('IDN_OAUTH2_TOKEN_BINDING'))
CREATE INDEX IDX_TK_VALUE_TYPE ON IDN_OAUTH2_TOKEN_BINDING (TOKEN_BINDING_VALUE, TOKEN_BINDING_TYPE);
