IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'IDN_OAUTH2_DEVICE_FLOW' AND COLUMN_NAME = 'QUANTIFIER')
BEGIN
    DECLARE @COMMAND NVARCHAR(200)
    SELECT @COMMAND='ALTER TABLE IDN_OAUTH2_DEVICE_FLOW DROP CONSTRAINT ' + CONSTRAINT_NAME + ';' FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME ='IDN_OAUTH2_DEVICE_FLOW' AND COLUMN_NAME='USER_CODE'
    EXEC (@COMMAND)
    ALTER TABLE IDN_OAUTH2_DEVICE_FLOW ADD QUANTIFIER INTEGER DEFAULT 0
    ALTER TABLE IDN_OAUTH2_DEVICE_FLOW ADD CONSTRAINT USRCDE_QNTFR_CONSTRAINT UNIQUE (USER_CODE, QUANTIFIER)
END

BEGIN TRANSACTION;
UPDATE IDP_METADATA SET NAME = 'account.lock.handler.lock.on.max.failed.attempts.enable'
WHERE NAME = 'account.lock.handler.enable';
COMMIT;
