/* User should have the Superuser permission */
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE UM_TENANT ADD COLUMN UM_TENANT_UUID VARCHAR(36) NOT NULL DEFAULT uuid_generate_v4();

ALTER TABLE UM_TENANT ADD UNIQUE (UM_TENANT_UUID);
