IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[IDN_FEDERATED_USER_TOTP_SECRET_KEY]') AND TYPE IN (N'U'))
CREATE TABLE IDN_FEDERATED_USER_TOTP_SECRET_KEY (
            USER_ID VARCHAR (255) NOT NULL,
            SECRET_KEY VARCHAR(1024) NOT NULL,
            PRIMARY KEY (USER_ID)
);
