ALTER TABLE UM_USER ADD COLUMN UM_USER_ID CHAR(36) NOT NULL DEFAULT 'NONE'/
CALL SYSPROC.ADMIN_CMD('REORG TABLE SP_APP')/

UPDATE SP_APP SET UM_USER_ID = NEWUUID()/
CALL SYSPROC.ADMIN_CMD('REORG TABLE SP_APP')/

ALTER TABLE SP_APP ADD UNIQUE (UM_USER_ID)/
CALL SYSPROC.ADMIN_CMD('REORG TABLE SP_APP')/

CREATE INDEX UUID_DM_UID_TID ON UM_UUID_DOMAIN_MAPPER (UM_USER_ID, UM_TENANT_ID)/
