IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[UM_USER]') AND TYPE IN (N'U'))
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UM_USER' AND COLUMN_NAME = 'UM_USER_ID')
ALTER TABLE UM_USER
    ADD UM_USER_ID CHAR(36) DEFAULT LOWER(NEWID()) NOT NULL,
    UNIQUE(UM_USER_ID);
