ALTER TABLE REG_RESOURCE_COMMENT ADD ID INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE REG_RESOURCE_COMMENT ADD PRIMARY KEY(ID);

ALTER TABLE REG_RESOURCE_RATING ADD ID INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE REG_RESOURCE_RATING ADD PRIMARY KEY(ID);

ALTER TABLE REG_RESOURCE_TAG ADD ID INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE REG_RESOURCE_TAG ADD PRIMARY KEY(ID);

ALTER TABLE REG_RESOURCE_PROPERTY ADD ID INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE REG_RESOURCE_PROPERTY ADD PRIMARY KEY(ID);

ALTER TABLE UM_SHARED_USER_ROLE ADD ID INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE UM_SHARED_USER_ROLE ADD PRIMARY KEY(ID);
