ALTER TABLE REG_RESOURCE_COMMENT ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;

ALTER TABLE REG_RESOURCE_RATING ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;

ALTER TABLE REG_RESOURCE_TAG ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;

ALTER TABLE REG_RESOURCE_PROPERTY ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;

ALTER TABLE UM_SHARED_USER_ROLE ADD ID INTEGER NOT NULL IDENTITY PRIMARY KEY;
