IF NOT EXISTS (SELECT * FROM SYS.indexes WHERE name = 'IDX_REMOTE_FETCH_REVISION_CONFIG_ID' and object_id = OBJECT_ID('IDN_REMOTE_FETCH_REVISIONS'))
CREATE INDEX IDX_REMOTE_FETCH_REVISION_CONFIG_ID ON IDN_REMOTE_FETCH_REVISIONS (CONFIG_ID);
