ALTER TABLE UM_DOMAIN
ALTER COLUMN UM_DOMAIN_NAME SET NOT NULL
/

ALTER TABLE UM_HYBRID_ROLE
ALTER COLUMN UM_ROLE_NAME SET NOT NULL
/

ALTER TABLE UM_SYSTEM_ROLE
ALTER COLUMN UM_ROLE_NAME SET NOT NULL
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  EXECUTE IMMEDIATE 'ALTER TABLE UM_DOMAIN DROP CONSTRAINT UC_UM_DOMAIN';
END
/
ALTER TABLE UM_DOMAIN ADD CONSTRAINT UC_UM_DOMAIN UNIQUE(UM_DOMAIN_NAME,UM_TENANT_ID)
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  EXECUTE IMMEDIATE 'ALTER TABLE UM_HYBRID_ROLE DROP CONSTRAINT UC_UM_HYBRID_ROLE';
END
/
ALTER TABLE UM_HYBRID_ROLE ADD CONSTRAINT UC_UM_HYBRID_ROLE UNIQUE(UM_ROLE_NAME,UM_TENANT_ID)
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  EXECUTE IMMEDIATE 'ALTER TABLE UM_SYSTEM_ROLE DROP CONSTRAINT UC_UM_SYSTEM_ROLE';
END
/
ALTER TABLE UM_SYSTEM_ROLE ADD CONSTRAINT UC_UM_SYSTEM_ROLE UNIQUE(UM_ROLE_NAME,UM_TENANT_ID)
/

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  EXECUTE IMMEDIATE 'ALTER TABLE UM_SYSTEM_ROLE DROP CONSTRAINT UNIQUE_REG_PATH_TENANT_ID';
END
/
ALTER TABLE UM_SYSTEM_ROLE ADD CONSTRAINT UNIQUE_REG_PATH_TENANT_ID UNIQUE(REG_PATH_VALUE,REG_TENANT_ID)
/


BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  EXECUTE IMMEDIATE 'DROP INDEX UM_ROLE_NAME_IND';
END
/
CREATE INDEX UM_ROLE_NAME_IND ON UM_HYBRID_ROLE(UM_ROLE_NAME)
/
