ALTER TABLE CM_SP_PURPOSE_PURPOSE_CAT_ASSC ADD ID INTEGER NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

ALTER TABLE CM_PURPOSE_PII_CAT_ASSOC ADD ID INTEGER NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

ALTER TABLE CM_SP_PURPOSE_PII_CAT_ASSOC ADD ID INTEGER NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

ALTER TABLE CM_CONSENT_RECEIPT_PROPERTY ADD ID INTEGER NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);
