BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  EXECUTE IMMEDIATE 'DROP INDEX IDX_TK_VALUE_TYPE';
END
/

CREATE INDEX IDX_TK_VALUE_TYPE ON IDN_OAUTH2_TOKEN_BINDING(TOKEN_BINDING_VALUE, TOKEN_BINDING_TYPE)
/

-- --------------------------- INDEX CREATION -----------------------------

-- IDN_OIDC_PROPERTY --
CREATE INDEX IDX_IOP_CK ON IDN_OIDC_PROPERTY(CONSUMER_KEY)
/

-- --------------------------- REMOVE UNUSED INDICES -----------------------------

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  -- IDN_OAUTH2_ACCESS_TOKEN --
  EXECUTE IMMEDIATE 'DROP INDEX IDX_AT_CK_AU';
  EXECUTE IMMEDIATE 'DROP INDEX IDX_AT_AU_TID_UD_TS_CKID';
  EXECUTE IMMEDIATE 'DROP INDEX IDX_AT_AU_CKID_TS_UT';
  -- IDN_OIDC_PROPERTY --
  EXECUTE IMMEDIATE 'DROP INDEX IDX_IOP_TID_CK';
END
/
