BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  EXECUTE IMMEDIATE 'DROP INDEX IDX_TK_VALUE_TYPE';
END
/

CREATE INDEX IDX_TK_VALUE_TYPE ON IDN_OAUTH2_TOKEN_BINDING(TOKEN_BINDING_VALUE, TOKEN_BINDING_TYPE)
/

-- --------------------------- INDEX CREATION -----------------------------

-- IDN_OIDC_PROPERTY --
CREATE INDEX IDX_IOP_CK ON IDN_OIDC_PROPERTY(CONSUMER_KEY)
/

-- --------------------------- REMOVE UNUSED INDICES -----------------------------

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704'
  BEGIN END;
  -- IDN_OAUTH2_ACCESS_TOKEN --
  EXECUTE IMMEDIATE 'DROP INDEX IDX_AT_CK_AU';
  EXECUTE IMMEDIATE 'DROP INDEX IDX_AT_AU_TID_UD_TS_CKID';
  EXECUTE IMMEDIATE 'DROP INDEX IDX_AT_AU_CKID_TS_UT';
  -- IDN_OIDC_PROPERTY --
  EXECUTE IMMEDIATE 'DROP INDEX IDX_IOP_TID_CK';
END
/

------------------------ ORGANIZATION MANAGEMENT TABLES -------------------------

CREATE TABLE IF NOT EXISTS SP_SHARED_APP (
	ID INTEGER NOT NULL,
	MAIN_APP_ID CHAR(36) NOT NULL,
	OWNER_ORG_ID CHAR(36) NOT NULL,
	SHARED_APP_ID CHAR(36) NOT NULL,
	SHARED_ORG_ID CHAR(36) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (MAIN_APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE,
	FOREIGN KEY (SHARED_APP_ID) REFERENCES SP_APP(UUID) ON DELETE CASCADE,
	UNIQUE (MAIN_APP_ID, OWNER_ORG_ID, SHARED_ORG_ID),
	UNIQUE (SHARED_APP_ID)
)
/

CREATE SEQUENCE SP_SHARED_APP_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE
/

CREATE TRIGGER SP_SHARED_APP_TRIG NO CASCADE
    BEFORE INSERT
    ON SP_SHARED_APP
    REFERENCING NEW AS NEW
    FOR EACH ROW MODE DB2SQL
        BEGIN ATOMIC
            SET (NEW.ID) = (NEXTVAL FOR SP_SHARED_APP_SEQUENCE);
        END
/

-------------------------GROUP ID DOMAIN MAPPER TABLES ----------------------------

CREATE TABLE UM_GROUP_UUID_DOMAIN_MAPPER (
    UM_ID INTEGER NOT NULL,
    UM_GROUP_ID VARCHAR(255) NOT NULL,
    UM_DOMAIN_ID INTEGER NOT NULL,
    UM_TENANT_ID INTEGER DEFAULT 0,
    PRIMARY KEY (UM_ID),
    UNIQUE (UM_GROUP_ID),
    FOREIGN KEY (UM_DOMAIN_ID, UM_TENANT_ID) REFERENCES UM_DOMAIN(UM_DOMAIN_ID, UM_TENANT_ID) ON DELETE CASCADE
)
/

CREATE SEQUENCE UM_GROUP_UUID_DOMAIN_MAPPER_SEQUENCE AS DECIMAL(27,0)
    INCREMENT BY 1
    START WITH 1
    NO CACHE
/

CREATE TRIGGER UMGROUP_UUID_DOMAIN_MAPPER NO CASCADE BEFORE INSERT ON UM_GROUP_UUID_DOMAIN_MAPPER
REFERENCING NEW AS NEW FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
    SET (NEW.UM_ID)
       = (NEXTVAL FOR UM_GROUP_UUID_DOMAIN_MAPPER_SEQUENCE);
END
/

CREATE INDEX UUID_GRP_UID_TID ON UM_GROUP_UUID_DOMAIN_MAPPER(UM_GROUP_ID, UM_TENANT_ID)
/
